resolver: lts-3.13
extra-deps: [ tasty-hspec-1.1.2 ]
packages:
  - "."
  - location:
      git: git@github.com:fpco/monad-logger-json-extra.git
      commit: dd40b3c96e67f41da984ba6d203c6c82b1932d00
    extra-dep: true
image:
  container:
    base: "hauth-base"
